### ISSUE TITLE
Gracefully handles the expression tree with custom Expression implementations

### ISSUE THREAD

**Issue by CXuesong** [zspitz/ExpressionTreeToString#76]
**Describe the bug**  
When working with `IQueryable`, I have an expression tree with some custom `Expression`-derived class inside. I want to visualize the expression tree but it fails.

**To Reproduce**  
Expression tree DebugView. Note there is an `Extension<WikiClientLibrary.Cargo.Linq.CargoQueryRootExpression>` node, which is a custom Expression class.
```c#
.Call System.Linq.Queryable.Where(
    .Call System.Linq.Queryable.Select(
        .Extension<WikiClientLibrary.Cargo.Linq.CargoQueryRootExpression>,
        '(.Lambda #Lambda1<System.Func`2[WikiClientLibrary.Tests.UnitTestProject1.Tests.CargoTests+LolSkin,<>f__AnonymousType1`3[System.String,System.String,System.DateTime]]>))
    ,
    '(.Lambda #Lambda2<System.Func`2[<>f__AnonymousType1`3[System.String,System.String,System.DateTime],System.Boolean]>))

.Lambda #Lambda1<System.Func`2[WikiClientLibrary.Tests.UnitTestProject1.Tests.CargoTests+LolSkin,<>f__AnonymousType1`3[System.String,System.String,System.DateTime]]>(WikiClientLibrary.Tests.UnitTestProject1.Tests.CargoTests+LolSkin $s)
{
    .New <>f__AnonymousType1`3[System.String,System.String,System.DateTime](
        $s.Name,
        $s.Champion,
        $s.ReleaseDate)
}

.Lambda #Lambda2<System.Func`2[<>f__AnonymousType1`3[System.String,System.String,System.DateTime],System.Boolean]>(<>f__AnonymousType1`3[System.String,System.String,System.DateTime] $s)
{
    $s.Champion == (.Constant<WikiClientLibrary.Tests.UnitTestProject1.Tests.CargoTests+<>c__DisplayClass3_0>(WikiClientLibrary.Tests.UnitTestProject1.Tests.CargoTests+<>c__DisplayClass3_0).closureParams).Champion
}
```

**Expected behavior**  
I assume I should still be able to see the rest part of the expression. Perhaps you can replace the unknown expressions with some placeholders, but for now I'm completely blocked from visualizing any part of the expression.

**Screenshots**  
![image](https://user-images.githubusercontent.com/11611687/101284183-a9db6e00-3819-11eb-89cb-40a4ed093c94.png)

**Version info:**

- Visual Studio version: 2019
- Visualizer location: [VS install path, or Documents subfolder]
- Version: 1.7.109

Note that the visualizer location and version can be found at the bottom of the **Settings** popup (click the gear icon).

**Additional context**

**Comment by zspitz** [comment]
@CXuesong Thanks for taking the time to report this.

I've transferred this issue here because it's a bug in the ExpressionTreeToString library, not the visualizer per se.

[`ValueExtractor`](https://github.com/zspitz/ExpressionTreeToString/blob/master/Library/ValueExtractor.cs) generates values for each node in the expression tree, by wrapping it in a `LambdaExpression` (if it isn't a `LambdaExpression`) and invoking the `LambdaExpression`.

I'm assuming that `CanReduce` on the extension node returns false? AFAICT the error comes about because it cannot be reduced, and therefore any nodes which refer to it should not be evaluated either.

I've committed a fix. Could you add the latest version of [ExpressionTreeToString (3.2.53 when it becomes available)](https://www.nuget.org/packages/ExpressionTreeToString/) to your project, and call `query.Expression.ToString("Textual tree")` in order to test the fix?

Also note that the fix will not immediately be available in the newest release of the visualizer. I'll let you know when that's finished.

**Comment by CXuesong** [comment]
> I'm assuming that CanReduce on the extension node returns false?

Yeah you can see the definition of `CargoQueryRootExpression` here: https://github.com/CXuesong/WikiClientLibrary/blob/db722959e3a921a8cba448dee1a80d433aaacd7c/WikiClientLibrary.Cargo/Linq/CargoQueryRootExpression.cs

It's by design not reduciable.

**Comment by CXuesong** [comment]
I've tried your latest version and it works. Thanks for your fast fix!

https://dotnetfiddle.net/SunZVv

**Comment by zspitz** [comment]
@CXuesong The [latest release of the visualizer](https://github.com/zspitz/ExpressionTreeVisualizer/releases/tag/1.7.110) includes the fix.
